### ISSUE TITLE
Serialise print output to avoid threads printing in same line

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/mbed-os-example-uvisor-number-store#17]
Log http://e108747.cambridge.arm.com:8080/job/mbed-os/job/e_g_pr_uvisor_number_store/8/console
shows line
```
13:14:08 [1485868420.65][CONN][RXD] 0: Permission denied. This client cannot write the secure number '0x00002: Re0019' ad '0
```
This indicates that two threads try to print at the same time causing unreadable texts. Also this is not deterministic and impacts example automation.

**Comment by mazimkhan** [comment]
Impacts https://github.com/ARMmbed/mbed-os-example-uvisor-number-store/pull/16 and https://github.com/ARMmbed/mbed-os-example-uvisor-number-store/pull/15

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-278

**Comment by AlessandroA** [comment]
This is now fixed.
