### ISSUE TITLE
[OOB_5_4_RC1] binary built from Makefile (make_gcc_arm) fails on K64F target

### ISSUE THREAD

**Issue by senthilr** [ARMmbed/mbed-os-example-uvisor-number-store#26]
# Symptom
mbed-os-example-uvisor-number-store.bin binary built from Makefile exported for ARM_GCC fails to execute on K64F with no output on the serial console

# Details
* export Makefile from mbed-CLI, build:
```
$mbed export -m K64F -i make_gcc_arm --profile develop
$make clean && make -j 4
```
* Also tried binary built from Makefile with DEBUG enabled and observed the same results. Obviously the resulting binary in this case is larger in size.
```
$mbed export -m K64F -i make_gcc_arm
$make clean && make -j 4
```

# Environment
```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
$ mbed --version
1.0.0
$ mbed ls
mbed-os-example-uvisor-number-store (cb6ca87e63d4)
`- mbed-os (3a27568a505b)
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSEC-299

**Comment by toyowata** [comment]
[mbed-os-example-uvisor](mbed-os-example-uvisor) is same result.

**Comment by 0xc0170** [comment]
Any update for this issue?

**Comment by AlessandroA** [comment]
This is a known issue (from the previous release). I've marked the exporters as "Do not test" in the OOB spreadsheet.
